SELECT DISTINCT
CONCAT(E.FIRST_NAME,' ',E.LAST_NAME)               AS Apenas_historico_completo
FROM EMPLOYEES E 
INNER JOIN JOB_HISTORY H ON E.EMPLOYEE_ID = H.EMPLOYEE_ID
INNER JOIN JOBS J ON H.JOB_ID = J.JOB_ID